# Dependency license and source policy. Run: cargo deny check

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
]
confidence-threshold = 0.8

[advisories]
ignore = []

[bans]
multiple-versions = "warn"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
